config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'services#index'

  #get 'services/new', to: 'services#new'
  #post 'services', to: 'services#create'
  #get 'services/:id', to: 'services#show', as: 'service'

  resources :services, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/service.rb
class Service < ApplicationRecord
  validates :name, :price, :duration, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # new, create, show, edit, update, destroy
  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    service_params = params.require(:service).permit(:name, :price, :duration, :description)
    # Hash = {name: "Serviço Teste", price: 123122 }
    @service = Service.new(service_params)

    if @service.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/index.html.erb
<h1>Services</h1>

<%= link_to 'Novo', new_service_path %>

<%- @services.each do |service| %>
  <ul>
    <li>Nome: <%= service.name %></li>
    <li>Preço: R$ <%= service.price %></li>
    <li>Duração: <%= service.duration %> minutos</li>
    <%- if service.description %>
      <li>Descrição: <%= service.description %></li>
    <%- end %>
    <li><%= link_to 'Ver mais', service_path(service) %></li>
  </ul>
<%- end %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%- @service.errors.messages.each do |field, errors| %>
  <p>Erro no campo <%= field %></p>
  <ul>
    <%- errors.each do |message| %>
      <li><%= message %>
    <%- end %>
  </ul>
<%- end %>

<%= form_for @service do |f| %>
  Nome:<br>
  <%= f.text_field :name %><br><br>

  Preço:<br>
  <%= f.text_field :price %><br><br>

  Duração:<br>
  <%= f.text_field :duration %><br><br>

  Descrição:<br>
  <%= f.text_area :description %><br><br>

  <%= f.submit 'Criar' %>
<%- end %>

app/views/services/show.html.erb
<h1><%= @service.name %></h1>